version: "3.9"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env   # contains OPENAI_API_KEY and PERPLEXITY_API_KEY
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_BASE=http://localhost:8000
