version: "3.9"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: [./server/.env]
    expose: ["8000"]
    restart: unless-stopped

web:
  build:
    context: ./web
    dockerfile: Dockerfile.prod
    args:
      VITE_API_BASE: http://api:8000
  ports:
    - "80:80"   # or if using nginx as above, use "80:80"

