version: "3.9"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: [./server/.env]
    expose: ["8000"]
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    depends_on: [api]
    ports: ["80:5173"]     # serve on 80
    environment:
      - VITE_API_BASE=http://api:8000
    restart: unless-stopped
