version: "3.9"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env   # OPENAI_API_KEY, PERPLEXITY_API_KEY
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped