name: stocks-ai
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env          # put OPENAI_API_KEY, PERPLEXITY_API_KEY here
    expose:
      - "8000"                 # internal only
    restart: unless-stopped

web:
  build:
    context: ./web
    dockerfile: Dockerfile.prod
    args:
      VITE_API_BASE: /api
  environment:
    - VITE_API_BASE=/api
  ports:
    - "80:80"

